return
    -- {
    --     "ixru/nvim-markdown"
    -- }
--  {
--     "tadmccorkle/markdown.nvim",
--     ft = "markdown", -- or 'event = "VeryLazy"'
--     opts = {
--         -- configuration here or empty for defaults
--     },
-- }

-- {
--   "epwalsh/obsidian.nvim",
--   version = "*",  -- recommended, use latest release instead of latest commit
--   lazy = true,
--   ft = "markdown",
--   -- Replace the above line with this if you only want to load obsidian.nvim for markdown files in your vault:
--   -- event = {
--   --   -- If you want to use the home shortcut '~' here you need to call 'vim.fn.expand'.
--   --   -- E.g. "BufReadPre " .. vim.fn.expand "~" .. "/my-vault/*.md"
--   --   -- refer to `:h file-pattern` for more examples
--   --   "BufReadPre path/to/my-vault/*.md",
--   --   "BufNewFile path/to/my-vault/*.md",
--   -- },
--   dependencies = {
--     -- Required.
--     "nvim-lua/plenary.nvim",
--
--     -- see below for full list of optional dependencies 👇
--   },
--   opts = {
--     workspaces = {
--       -- {
--       --   name = "personal",
--       --   path = "~/vaults/personal",
--       -- },
--       {
--         name = "work",
--         path = "/Users/bogdan/Library/Mobile Documents/iCloud~md~obsidian/Documents/Work",
--       },
--     },
--
--     -- see below for full list of options 👇
--   },
-- }

-- {
--         'vimwiki/vimwiki'
--     }

-- {
-- 'bullets-vim/bullets.vim'
--     }
-- {
--   "roodolv/markdown-toggle.nvim",
--   config = function()
--     require("markdown-toggle").setup({
--                 use_default_keymaps = true,
--             })
--   end,
-- }


-- TODO:
-- - [ ] Unordered list / Ordered lists / checkboxes
--     - [ ] o / O / Enter - inserts new entry
--     - [ ] Order number is updated
--     - [ ] n_>> / n_<< / v_> / v_< / Tab - shifts item and updates order
--     - [ ] Enter shifts back or toggles no list bullet
-- - [ ] Toggle checkboxes (make list item and toogle it)
--     - [ ] toggle states waiting/canceled/done/not done
-- - [ ] Toggle headers (increase/decrease)
-- - [ ] inset links
-- - [ ] tables extansion on enter/tab
